version: '3.1'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_3.1.5_container
    ports:
      - 80:80
    volumes:
      - /Users/jachobmollegard/Desktop/KEA WEB/1_web_development/x_docker:/app
    networks:
      - bottle_arangodb_network

  arangodb:
    image: arangodb:3.11.3
    container_name: x_arango_3.11.3_container
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - /Users/jachobmollegard/Desktop/KEA WEB/1_web_development/x_docker/arangodb:/var/lib/arangodb3
    networks:
      - bottle_arangodb_network

networks:
  bottle_arangodb_network:
